### ISSUE TITLE
Error to install icon bug [access denied issue]

### ISSUE THREAD

**Issue by rraffaelandrei** [MishaProductions/Rectify11Installer#109]
### Description

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
at Rectify11Installer.Core.ShellLink.IPersistFile.Save(String pszFileName, Boolean fRemember)
at Rectify11Installer.Core.ShellLink.Save(String linkFile) in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\ShellLink.cs:line 1027
at Rectify11Installer.Core.Installer.FixOdbc() in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\Installer.cs:line 344
at Rectify11Installer.Core.Installer.b__2_29() in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\Installer.cs:line 278
at System.Threading.Tasks.Task1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter

### Steps To Reproduce

no

### Rectify11 Version

latest commit

### Windows Version

windows 11 21h2

### Logs

![Screenshot 2023-02-12 235826](https://user-images.githubusercontent.com/91460382/218690829-3c049c7c-4b15-4c6c-84f4-d06f5392a187.png)

**Comment by rraffaelandrei** [comment]
i make new issue cuz was too much comments
